# -*- coding: utf-8 -*-
"""TP3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UqZ4VzwcpWQ4RP6mT8bN9Sx1BjgWSMZQ
"""

import math


def powerint (x, p): 
  '''x: base; p:potencia
    devuelve x^p'''


  if x > 0:
    y = 1
    if p<0:
      x = 1/x
      p *= -1
    
    if p != 0:
      for i in range(p):
        y *= x 
    
    return y
 
  else:
     return 0

def myfunc(point, q, y): 
  '''Esta función es la que se evalúa para despejar 
  por biyección point = y^(1/q)'''
  a = powerint(point,q) - y
  return a

def powerrat (x, p, q):
  
  y = powerint(x, p)
  
  if q<0:
    y = 1/y
    q *= -1
  
  tol = 0.0001
  
  a = 0
  b = 10

  while  myfunc(a,q,y)*myfunc(b,q,y)>0:
    print(myfunc(a,q,y),myfunc(b,q,y))
    b+=1000

  for i in range(1000):
    c = (a+b)/2
    if (b-a)>tol: 
      if myfunc(a,q,y)*myfunc(c,q,y)>0:
        a = c
      else:
        b = c
    else:
      #print(c, b, a)
      return c
  #print(c, b, a)
  return c

print(powerrat (2,3, -4))